### ISSUE TITLE
Debug informations on prod

### ISSUE THREAD

**Issue by launtony** [elkarbackup/elkarbackup#256] opened 2017-11-29 10:19 UTC
Thanks for your very good product :) 

I'm using Elkarbackup with docker with the latest tag (1.2.6) and when I look the backup view, I have the full path of binary zip file (see screenshot) :) It's the good behavior? 

![screen shot 2017-11-29 at 11 14 13](https://user-images.githubusercontent.com/6367604/33370159-08ee48ce-d4f7-11e7-9014-de676da3cbaf.png)

**Comment by xezpeleta** [comment] 2017-11-29 12:49
I'd say is a small bug, but I can't reproduce it in my production server.

What linux distro are you using as server?

Thanks

**Comment by launtony** [comment] 2017-11-29 13:08
Thanks for your feedback :) I'm using Debian 9 strech

**Comment by launtony** [comment] 2017-12-04 09:25
Any news ? :)

**Comment by xezpeleta** [comment] 2017-12-10 20:52
@launtony it should be fixed in the next version :)

**Comment by launtony** [comment] 2017-12-11 06:51
Nice :)

**Closed** 2018-02-12 12:02 UTC
Labels: bug, fixed
