### ISSUE TITLE
Elkarbackup wants to upgrade over and over again / stops with a PHP Warning

### ISSUE THREAD

**Issue by FezziFezzino** [elkarbackup/elkarbackup#412] opened 2020-05-28 10:23 UTC
Hi there,
so far Elkarbackup is running great. 
However, it wants to upgrade over and over again when I run upgrades on the machine.
The error which I get is:
`Preconfiguring packages ...
(Reading database ... 206260 files and directories currently installed.)
Preparing to unpack .../elkarbackup_1.3.3_all.deb ...
Unpacking elkarbackup (1.3.3) over (1.3.3) ...
Setting up elkarbackup (1.3.3) ...
Using /etc/elkarbackup/parameters.yml configuration ok
DB seems to be ready
Adding missing parameters as required
Delete cache content
Update DB
PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /usr/share/elkarbackup/vendor/symfony/monolog-bundle/DependencyInjection/Configuration.php on line 628
Create root user
Clean cache
PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /usr/share/elkarbackup/vendor/symfony/monolog-bundle/DependencyInjection/Configuration.php on line 628
Dump assests
Invalidate sessions
Processing triggers for ureadahead (0.100.0-21) ...
Processing triggers for systemd (237-3ubuntu10.41) ...
`
Line 628 in the Configuration.php looks like this:
` ->ifTrue(function ($v) { return ('fingers_crossed' === $v['type'] || 'buffer' === $v['type'] || 'filter' === $v['type']) && 1 !== count($v['handler']); })`

Thx in advance for any hint's / idea's how to solve it.

**Comment by elacunza** [comment] 2021-01-18 15:45
Did you solve this? What distro and version?

**Comment by FezziFezzino** [comment] 2021-01-19 02:12
Hi there,
nope, didn't find the problem yet. However, got used to the error message and all is running fine. 
Running Ubuntu 18.04.5 LTS
Will of course report here when I find a solution.

**Comment by elacunza** [comment] 2021-01-26 17:18
Warnings should not be an issue.
Can you send the output of:
dpkg -l|grep elkarbackup 
?

**Comment by FezziFezzino** [comment] 2021-01-27 04:21
Hi Eneko,
thx for looking in to it... here the output of...
dpkg -l|grep elkarbackup
ii  elkarbackup                                1.3.4
                     all          backup solution with an easy-to-use web
interface based on Rsync / RSnapshot

Elcarbackup is running fine so far.. below again the output of one of the
countless upgrade attempts...

Preconfiguring packages ...
(Reading database ... 383060 files and directories currently installed.)
Preparing to unpack .../elkarbackup_1.3.4_all.deb ...
Unpacking elkarbackup (1.3.4) over (1.3.4) ...
Setting up elkarbackup (1.3.4) ...
Using /etc/elkarbackup/parameters.yml configuration ok
DB seems to be ready
Adding missing parameters as required
Delete cache content
Update DB
PHP Warning:  count(): Parameter must be an array or an object that
implements Countable in
/usr/share/elkarbackup/vendor/symfony/monolog-bundle/DependencyInjection/Configuration.php
on line 628
Create root user
Clean cache
PHP Warning:  count(): Parameter must be an array or an object that
implements Countable in
/usr/share/elkarbackup/vendor/symfony/monolog-bundle/DependencyInjection/Configuration.php
on line 628
Dump assests
Invalidate sessions
Processing triggers for ureadahead (0.100.0-21) ...
Processing triggers for systemd (237-3ubuntu10.44) ...

**Comment by elacunza** [comment] 2021-01-27 10:03
Thanks, really weird because it upgraded correctly to 1.3.4 but the problem continues.
I'll try to reproduce it on an updated Ubuntu 18.04 and will report back.

**Comment by elacunza** [comment] 2021-04-21 16:13
I can't reproduce this issue.

Did you try removing and reinstalling again?
apt-get remove elkarbackup
apt-get install elkarbackup

**Comment by FezziFezzino** [comment] 2021-04-22 05:08
Yes, I did... same thing... but don't spend any time on it... as I wrote previously, it is just a cosmetic error as elcarbackup is running fine despite this update thing... ;)
Once elcarbackup is running under Ubuntu 20.04 LTS I will do a upgrade from 18.04 to 20.04 anyway and then we will see if it persists... 
Thx for your time looking in to it... but just drop it... better spend time on the new version which can run under 20.04
Stay safe and helathy.. cheers

**Comment by elacunza** [comment] 2021-04-22 08:09
Thanks a lot, closing this then.

**Closed by elacunza** 2021-04-22 08:09 UTC
Labels: contributor/need-more-information, kind/bug/possible
