### ISSUE TITLE
Bug 'Not found' when I used clone features

### ISSUE THREAD

**Issue by launtony** [elkarbackup/elkarbackup#258] opened 2017-12-07 16:36 UTC
After using clone feature, the edit mode (customer clone) call a 404 Not found :/ 

http://[IP]/client/:id     not     http://[IP]/elkarbackup/client/:id

**Comment by xezpeleta** [comment] 2017-12-10 19:15
Hi @launtony 

If you are accessing Elkarbackup using the URL http://[IP]/elkarbackup then you must define the `URL prefix=/elkarbackup` (Settings icon -> Manage Parameters)

That should fix your issue

**Comment by launtony** [comment] 2017-12-11 06:50
Thanks for your reply :)

**Comment by launtony** [comment] 2017-12-13 11:08
I have put the URL prefix but I have the same problem :/ When I used the clone refresh without refresh the main page, when I would edit the clone with the brush button I have a 404 Not Found :/

**Comment by xezpeleta** [comment] 2017-12-16 18:20
I'm sorry, but I'm not able to reproduce your issue.

Do you see the prefix value in settings changed?
Does it still redirect you to `http://<ip-address>/client/<id>` ?
Could you add screenshots?

**Comment by launtony** [comment] 2017-12-20 22:45
No I didn't saw the prefix :/ You can look the pictures : 

<img width="657" alt="screen shot 2017-12-20 at 23 42 00" src="https://user-images.githubusercontent.com/6367604/34232270-d70f5f88-e5df-11e7-9f9f-df332e528009.png">
<img width="1266" alt="screen shot 2017-12-20 at 23 42 16" src="https://user-images.githubusercontent.com/6367604/34232271-d72449c0-e5df-11e7-8074-d9aa6cb965af.png">
<img width="1136" alt="screen shot 2017-12-20 at 23 42 32" src="https://user-images.githubusercontent.com/6367604/34232272-d7393f6a-e5df-11e7-8a88-d8dbe9f6006f.png">
<img width="1393" alt="screen shot 2017-12-20 at 23 42 56" src="https://user-images.githubusercontent.com/6367604/34232273-d74e0f6c-e5df-11e7-9908-333a958d5e98.png">

**Comment by launtony** [comment] 2018-01-03 08:32
Do you have any news about this problem?

**Comment by xezpeleta** [comment] 2018-02-12 08:22
Now yes, I can reproduce the bug! Give me some time to fix it, I'll keep you updated.

**Comment by launtony** [comment] 2018-02-12 08:27
Good news :)

**Comment by xezpeleta** [comment] 2018-02-14 10:47
It will be fixed in the upcoming version (v1.2.8)

**Closed by xezpeleta** 2018-02-14 10:47 UTC
Labels: bug
