### ISSUE TITLE
1.2 beta cannot start backup jobs

### ISSUE THREAD

**Issue by tjfayaz** [elkarbackup/elkarbackup#136] opened 2016-04-27 10:41 UTC
Hi, this new version is very promising I must say - great work! I've just upgraded to the beta version as I wanted some of the new features but now the problem I am having is my backup jobs will not run. 

If I create a fresh job and try and run it with "run now" I get the below error.

RequestError: Unable to load /elkarbackup/client/9/job/9/run status: 0

![screen shot](https://cloud.githubusercontent.com/assets/18698591/14850219/80fa7150-0c6f-11e6-94d6-d3f39d3e3077.png)

Any ideas what this could be?

**Comment by antton** [comment] 2016-04-27 11:13
You can try to clear the system cache.

sudo php /usr/share/elkarbackup/app/console cache:clear && sudo php /usr/share/elkarbackup/app/console assetic:dump

or just only /usr/share/elkarbackup/app/console c:c --env=prod

And try again.

**Comment by tjfayaz** [comment] 2016-04-27 11:17
done that, logged out and back in but same same error when I try to run jobs

**Comment by antton** [comment] 2016-04-27 11:51
What about /var/log/elkarbackup/prod.log file?

Can you check if it's also empty?

**Comment by tjfayaz** [comment] 2016-04-27 12:03
no no errors in /var/log/elkarbackup/prod.log 

I'm stumped

**Comment by tjfayaz** [comment] 2016-04-27 12:37
I also enabled full mysql logging and checked that but no queries go against it when I click to run the job so I guess it's something else at fault.

**Comment by antton** [comment] 2016-04-27 12:48
What was your previous version before than upgrade?

1.1.5? or really old one?

**Comment by xezpeleta** [comment] 2016-04-27 12:50
Yes, apparently there is a bug in 1.2-beta1 and "Run now" button only works over HTTPS.

@tjfayaz just to check, can you try to connect with HTTPS?

Thanks

**Comment by tjfayaz** [comment] 2016-04-27 12:57
switched to HTTPS and same problem

**Comment by tjfayaz** [comment] 2016-04-27 12:59
my prevous version was 1.1.5 - fully working. Tried deleting and createing new jobs but still they give that error.

**Comment by xezpeleta** [comment] 2016-04-27 13:02
Ok, last try:

1- Generate a "token" (Job->Edit->Advanced)
2- Run this command from another computer (where client id = 1 and job id= 2):

```sh
curl -k -d "token=0602f4a69af07fcb1327cc8d3f1371e7" https://192.168.33.10/client/1/job/2/run
```
Does it work?

Thanks

**Comment by tjfayaz** [comment] 2016-04-27 13:50
that makes it work, thank you ! So now I know how to make jobs run manually :)

So, do you think the job schedules will run? Or will they fail too? 

Does this make it work next time from the "run now"?

**Comment by tjfayaz** [comment] 2016-04-27 15:53
ok thanks for your fast responses guys. after that token generation ALL jobs are working now and I can start them manually. 

You guys are legend.

**Comment by xezpeleta** [comment] 2016-04-27 16:27
Job schedules should work without problems.

We'll try to fix this bug as soon as possible and release a new beta version. We're also working on some small GUI improvements. Once they are done, we'll be ready for the stable version.

Thanks

**Comment by xezpeleta** [comment] 2016-04-27 18:37
I'm checking it in my development environment and apparently the "Run now" button does not work when you access by HTTP.

prod.log
```
[2016-04-27 18:10:19] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "OPTIONS /elkarbackup/client/1/job/1/run"" at /opt/elkarbackup/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php line 176 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"OPTIONS /elkarbackup/client/1/job/1/run\" at /opt/elkarbackup/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php:176, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /opt/elkarbackup/app/cache/prod/appProdUrlMatcher.php:439)"} []
```

Using HTTPS works well in my case.

**Comment by xezpeleta** [comment] 2016-04-27 20:34
Hi @tjfayaz 

I think it's fixed, could you try the [patch](https://github.com/xezpeleta/elkarbackup/commit/852c0ff9073b3d7c33d23bb7a68084df5181c1c1.patch)?

To apply the patch:
```
cd /usr/share/elkarbackup
patch -p1 < 137-runJobAction-bug.patch
/usr/share/elkarbackup/app/console c:c --env=prod
/usr/share/elkarbackup/app/console a:d --env=prod
```
Thanks

**Comment by tjfayaz** [comment] 2016-04-27 20:54
Hi I'll try it in morning and mag back... But my jobs all run fine now so not sure what to check 

Sent from my iPhone

> On 27 Apr 2016, at 21:35, Xabi <notifications@github.com> wrote:
> 
> Hi @tjfayaz
> 
> I think it's fixed, could you try the patch?
> 
> To apply the patch:
> 
> cd /usr/share/elkarbackup
> patch -p1 < 137-runJobAction-bug.patch
> /usr/share/elkarbackup/app/console c:c --env=prod
> /usr/share/elkarbackup/app/console a:d --env=prod
> Thanks
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> 

This email and its attachments may be confidential and are intended solely for the use of the individual to whom it is addressed. Any views or opinions expressed are solely those of the author and do not necessarily represent those of With Support Limited. If you are not the intended recipient of this email and its attachments, you must take no action based upon them, nor must you copy or show them to anyone. Please contact the sender if you believe you have received this email in error.

**Comment by xezpeleta** [comment] 2016-04-28 13:55
@tjfayaz you told us your "Run now" button does not work.

In theory this patch will fix your issue - https://github.com/elkarbackup/elkarbackup/issues/136#issuecomment-215219640

Could you check that?

**Comment by tjfayaz** [comment] 2016-04-28 14:09
I did this and since then yesterday the jobs work, so should I still apply this patch? The only problem I have now is some jobs are stuck "running" and will not abort!

> 1- Generate a "token" (Job->Edit->Advanced)
> 2- Run this command from another computer:
> 
> curl -k -d "token=0602f4a69af07fcb1327cc8d3f1371e7" https://192.168.33.10/client/1/job/2/run
>

**Comment by xezpeleta** [comment] 2016-04-28 14:20
> I did this and since then yesterday the jobs work, so should I still apply this patch?

That curl command it's a way to run the job remotely. But your "Run now" button is probably still not working until you apply the above patch. By the way, that would help us to check if the bug is already fixed or not.

> The only problem I have now is some jobs are stuck "running" and will not abort!

So some jobs are like "running"... but can you see any rsnapshot process with `ps aux`? any "du" process?

Anyway, I think this problem should be reviewed in a new Issue. If you want, you can open a new one and add your logs to check what happened.

Thanks

**Comment by tjfayaz** [comment] 2016-04-28 14:31
root@ubuntu:/usr/share/elkarbackup# patch -p1 < 137-runJobAction-bug.patch
can't find file to patch at input line 15
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|From 852c0ff9073b3d7c33d23bb7a68084df5181c1c1 Mon Sep 17 00:00:00 2001
|From: Xabi Ezpeleta <xezpeleta@gmail.com>
|Date: Wed, 27 Apr 2016 19:55:48 +0000
|Subject: [PATCH] runJobAction: require HTTPS for anonymous petitions (#136)
|
|---
| app/config/security.yml                            |  5 ++---
| .../Controller/DefaultController.php               | 24 ++++++++++++++--------
| 2 files changed, 18 insertions(+), 11 deletions(-)
|
|diff --git a/app/config/security.yml b/app/config/security.yml
|index 698b90a..5a99981 100644
|--- a/app/config/security.yml
|+++ b/app/config/security.yml
--------------------------
File to patch:

**Comment by xezpeleta** [comment] 2016-04-28 16:05
Ok I see. There is an error applying the patch due to a symlink...

Can you try the following commands?

```sh
cd /usr/share/elkarbackup/app/config
patch security.yml < /usr/share/elkarbackup/137-runJobAction-bug.patch
# Ignore errors ("Hunk Failed")
cd /usr/share/elkarbackup/src/Binovo/ElkarBackupBundle/Controller
patch DefaultController.php < /usr/share/elkarbackup/137-runJobAction-bug.patch
# Ignore errors ("Hunk Failed")
```

Thanks

**Comment by xezpeleta** [comment] 2016-04-30 18:45
Another user has confirmed that this PR fixed the bug, so I'm closing this issue

**Closed by xezpeleta** 2016-04-30 18:45 UTC
Labels: bug, elkarbackup1.2
